### ISSUE TITLE
Base Lore

### ISSUE THREAD

**Issue by chamik** [radeksoft/prsi#1]
Vymyslet základ příběhu, tím pádem i celé hry

**Comment by milujuweed** [comment]
dyk dej mě sem taky bitch

**Comment by milujuweed** [comment]
a nvm

**Comment by SwitchyCZ** [comment]
cO je vlastně augustin

**Comment by jiklop123** [comment]
lol

**Comment by Radkuvprejt** [comment]
[Es regnet.docx](https://github.com/radeksoft/prsi/files/4684452/Es.regnet.docx)

**Comment by chamik** [comment]
Po několika dlouhých týdnech díky @Joe007elite něco konečně máme. :clap:
